export enum ControlTypesEnum {
  TEXT = 'text',
  INPUT = 'input',
  TEXTAREA = 'textarea',
  CHECKBOX = 'checkbox',
  RADIO = 'radio',
  SELECT = 'select',
  DATE = 'date',
  TIME = 'time',
  COLOR = 'color',
  FILE = 'file',
  NUMBER = 'number',
  EMAIL = 'email',
  PASSWORD = 'password',
  URL = 'url',
  SEARCH = 'search',
  TEL = 'tel',
  RANGE = 'range',
  HIDDEN = 'hidden',
  SUBMIT = 'submit',
  RESET = 'reset',
  IMAGE = 'image',
  BUTTON = 'button',
  EMPTY = 'empty',
}
